[package]
name = "tle-parser"
version = "0.1.0"
authors = ["Kazushi Kawamura <wakaka2277@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.0"
